name = "PositionalEmbeddings"
uuid = "d504d84d-5e64-4f13-be9b-c14c41279bd1"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com> and contributors"]
version = "0.5.0"

[deps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"

[compat]
CUDA = "5.5"
Functors = "0.4, 0.5"
Zygote = "0.6"
julia = "1.9"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "CUDA", "Zygote"]
